---
title: "Garden Map"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: bootstrap
    navbar:
       - { title: "Explore Health Conditions", href: health.html, align: left }
       - { title: "Explore Economic Investment", href: property_values.html, align: left }
       - { title: "Back to Home", href: index.html, align: right }
       
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(leaflet)
library(rgdal)
library(sp)
library(reactable)

#Set global theme for plots
theme_set(theme_minimal() + 
            theme(legend.position = "bottom", 
                  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)))
#Set options for all plots
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

```{r, include = FALSE}
garden =
  read_csv("./data/final_unique_boards.csv") %>%
  group_by(community_board) %>%
  select(id_spatial, garden_num, community_board, borough, overall_pop, race_white:college_higher)

garden_all = 
  read_csv("./data/final_unique_gardens.csv")

leafIcons <- icons(
  iconUrl = "http://leafletjs.com/examples/custom-icons/leaf-green.png",
  iconWidth = 10, iconHeight = 20
)

working <- getwd()
com_board_spdf <- readOGR(dsn = working, layer = "community_board_new")
names(com_board_spdf)
data_spatial <- merge(com_board_spdf, garden, by.x = "boro_cd", by.y = "id_spatial")
  
```


Column {data-width=400}
-----------------------------------------------------------------------

### Garden locations around New York

<style type="text/css">

.chart-title {  /* Garden locations around New York  */
   font-size: 20px;

</style>


```{r,  message = FALSE, warning = FALSE}

garden_all = 
  garden_all %>%
     mutate(
      click_label =
        str_c("<b>", garden_name, "</b><br>", size, " acres"))


# Prepare the text for labels:
mytext <- paste(
    "Borough: ", data_spatial@data$borough,"<br/>",
    "Community Board: ", data_spatial@data$community_board,"<br/>", 
    "Number of Gardens: ", data_spatial@data$garden_num, "<br/>", 
    sep = "") %>%
  lapply(htmltools::HTML)
 
# Final Map with shaded colors by number of gardens in the community district
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%  
  setView( lat = 40.7, lng = -74 , zoom = 10) %>%
  addPolygons(data = data_spatial,
    fillOpacity = 0, 
    smoothFactor = 0.5, 
    stroke = TRUE, 
    color = "black", 
    weight = 1,
    label = mytext,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto"
    )
  ) %>% 
    addMarkers(data = garden_all, ~longitude, ~latitude, icon = leafIcons, popup = ~click_label)

```

> Outlined community boards and individual garden locations.
> Label text specifies the total number of gardens in a given community board. Gardens were designated as being part of a community board based on their community board label in the original gardens dataset, therefore gardens without latitude and longitude values (n = 111) are included in the label text but not as an individual data point on the map (garden data last updated in 2017).

Column {.tabset .tabset-fade data-width=400}
-----------------------------------------------------------------------

### Age Distributions

```{r}

age_tables =
  garden_all %>% 
  select(borough, community_board, age0to17:age65plus) %>% 
  distinct()

colnames(age_tables) = c("Borough", "Community Board", "0 to 17 years", "18 to 24 years", "25 to 44 years", "45 to 64 years", "65 plus")

reactable(age_tables, groupBy = "Borough",highlight = TRUE, searchable = TRUE, striped = FALSE, fullWidth = FALSE, showSortIcon = FALSE, 
          theme = reactableTheme(
    borderColor = "#89C281",
    highlightColor = "#C0DCBC"), 
    defaultColDef = colDef(
      align = "left",
      minWidth = 100),
    columns = list(
  'Community Board' = colDef(),
  "0 to 17 years" = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%")),
  "18 to 24 years" = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%")),
  "25 to 44 years" = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%")),
  "45 to 64 years" = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%")),
  "65 plus" = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%"))))

```

> Proportion of age categories in each community board (data collected from 2012 - 2016).

### Education Distribution

```{r}

edu_tables =
  garden_all %>% 
  select(borough, community_board, not_complete_hs:college_higher) %>% 
  distinct()

edu_tables = 
  edu_tables %>% 
 relocate(not_complete_hs, .after = community_board)

colnames(edu_tables) = c("Borough", "Community Board", "Less than High School", "High School/Some College", "College or higher")

reactable(edu_tables, groupBy = "Borough", highlight = TRUE, searchable = TRUE, striped = FALSE, fullWidth = FALSE, showSortIcon = FALSE,
          theme = reactableTheme(
    borderColor = "#89C281",
    highlightColor = "#C0DCBC"), defaultColDef = colDef(
      align = "left",
      minWidth = 100),
    columns = list(
  'Community Board' = colDef(),
  "Less than High School" = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%"), width = 150),
  "High School/Some College" = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%"), width = 150),
  "College or higher" = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%"), width = 150)))
```

> Proportion of education levels in each community board (data collected from 2012 - 2016).

### Race Distributions

```{r}

race_tables =
  garden_all %>% 
  select(borough, community_board, race_white:race_other) %>% 
  distinct()

colnames(race_tables) = c("Borough", "Community Board", "White", "Black", "Asian", "Latino", "Other")

reactable(race_tables, highlight = TRUE, searchable = TRUE, striped = FALSE, fullWidth = FALSE, showSortIcon = FALSE, 
          theme = reactableTheme(
    borderColor = "#89C281",
    highlightColor = "#C0DCBC"),
          groupBy = "Borough", defaultColDef = colDef(
      align = "left",
      minWidth = 100),
    columns = list(
  "Community Board" = colDef(),
  White = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%")),
  Black = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%")),
  Asian = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%")),
  Latino = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%")),
  Other = colDef(aggregate = "mean", format = colFormat(digits = 2, suffix = "%"))))

```

> Proportion of race categories in each community board (data collected from 2012 - 2016).